create or replace NONEDITIONABLE FUNCTION CALCULAR_INGRESOS_TOTALES(P_ID_MUSEO NUMBER) RETURN NUMBER 
IS 
IN_TOTALES NUMBER;
BEGIN
SELECT SUM(T.PRECIO)INTO IN_TOTALES
    FROM TICKETS T
    WHERE T.ID_MUSEO=P_ID_MUSEO;
    
  RETURN IN_TOTALES;
END CALCULAR_INGRESOS_TOTALES;