create or replace NONEDITIONABLE PROCEDURE INGRESOS_TOTALES_MUSEO(P_ID_MUSEO NUMBER) AS 
   PRECIO NUMBER;
BEGIN
   PRECIO := CALCULAR_INGRESOS_TOTALES(p_id_museo);
   DBMS_OUTPUT.PUT_LINE('Precio calculado: ' || PRECIO);
END;