drop role empleado;
drop role restaurador;
drop role CURADOR;
drop role director;
drop role RRHH;
drop role MANTENIMIENTO;

CREATE role EMPLEADO;
Grant SELECT on EMPLEADOS_PROFESIONALES to EMPLEADO;
Grant SELECT on FORMACIONES to EMPLEADO;
Grant SELECT on HIST_EMPLEADOS to EMPLEADO;


CREATE role RESTAURADOR;

Grant SELECT on HIST_MOV_OBR_REST to RESTAURADOR;
Grant SELECT, UPDATE, INSERT on MANTENIMIENTOS_OBRAS_REALIZADOS to RESTAURADOR;
GRANT SELECT, UPDATE, INSERT on PROGRAMAS_MANT to RESTAURADOR;	


CREATE role CURADOR;
Grant SELECT, UPDATE, INSERT on HIST_OBRAS_MOV to CURADOR;
Grant SELECT, UPDATE, INSERT, DELETE on COLECCIONES_PERMANENTES to CURADOR;
Grant SELECT, UPDATE, INSERT on OBRAS to CURADOR;
Grant SELECT, UPDATE, INSERT on ARTISTAS to CURADOR;
Grant SELECT, UPDATE, INSERT, DELETE on SALAS_COLECCIONES to CURADOR;
Grant SELECT, UPDATE, INSERT on ARTISTAS_OBRAS to CURADOR;
Grant SELECT, UPDATE, INSERT on PROGRAMAS_MANT to CURADOR;
Grant SELECT, UPDATE, INSERT on  MANTENIMIENTOS_OBRAS_REALIZADOS to CURADOR;
Grant SELECT on SALAS_EXP to CURADOR;


CREATE role DIRECTOR;

Grant SELECT on MUSEOS to DIRECTOR;
Grant SELECT on TICKETS to DIRECTOR;
Grant SELECT on TIPO_TICKETS to DIRECTOR;
Grant SELECT on EXPOSICIONES_EVENTOS to DIRECTOR;
Grant SELECT on HIST_MUSEOS to DIRECTOR;


CREATE role RRHH;

Grant SELECT, UPDATE, INSERT on FORMACIONES to RRHH;
Grant SELECT, UPDATE, INSERT on IDIOMAS to RRHH;
Grant SELECT, UPDATE, INSERT on EMPLEADOS_IDIOMAS to RRHH;
Grant SELECT, UPDATE, INSERT on HIST_EMPLEADOS to RRHH;
Grant SELECT, UPDATE, INSERT on EMPLEADOS_PROFESIONALES to RRHH;
Grant SELECT, UPDATE, INSERT, DELETE on EMPLEADOS_VIGILANTE_MANT to RRHH;
Grant SELECT on EST_ORGANIZACIONAL to RRHH;

CREATE role MANTENIMIENTO;

Grant SELECT on ASIGNACIONES_MES to MANTENIMIENTO;
Grant SELECT on EMPLEADOS_VIGILANTE_MANT to MANTENIMIENTO;


--herencias de empleado
Grant empleado to restaurador;
Grant empleado to CURADOR;
Grant empleado to DIRECTOR;
Grant empleado to RRHH;
Grant empleado to MANTENIMIENTO;





