DROP ROLE CURADOR;
DROP ROLE RESTAURADOR;
DROP ROLE RRHH;
DROP ROLE DIRECTOR;
DROP ROLE VISITANTE;
DROP ROLE TAQUILLA;
DROP ROLE VIGILANTE_MANTENIMIENTO;

-- ROLES PARA USUARIOS
CREATE ROLE CURADOR;
CREATE ROLE RESTAURADOR;
CREATE ROLE RRHH;
CREATE ROLE DIRECTOR;
CREATE ROLE VISITANTE;
CREATE ROLE TAQUILLA;
CREATE ROLE VIGILANTE_MANTENIMIENTO;

GRANT CREATE SESSION TO CURADOR;
GRANT CREATE SESSION TO RESTAURADOR;
GRANT CREATE SESSION TO RRHH;
GRANT CREATE SESSION TO DIRECTOR;
GRANT CREATE SESSION TO VISITANTE;  
GRANT CREATE SESSION TO TAQUILLA;
GRANT CREATE SESSION TO VIGILANTE_MANTENIMIENTO;


-- PRIVILEGIOS DE UN CURADOR
--EL CURADOR SELECCIONA, ORGANIZA, INTERPRETA Y PRESENTA LAS OBRAS. LES ASIGNA SU PROGRAMA DE MANTENIMIENTO Y ADEMAS LES PUEDE HACER MANTENIMIENTO
--PRIVILEGIOS EN LO QUE RESPECTA AL REGISTRO DE OBRAS
GRANT SELECT, INSERT, UPDATE, DELETE ON DBMUSEO.ARTISTAS TO CURADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBMUSEO.OBRAS TO CURADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBMUSEO.ARTISTAS_OBRAS TO CURADOR;
GRANT SELECT, INSERT, UPDATE ON DBMUSEO.HIST_OBRAS_MOV TO CURADOR;
GRANT SELECT ON DBMUSEO.LUGARES TO CURADOR;
--PRIVILEGIOS EN LO QUE RESPECTA A LA PRESENTACION DE OBRAS EN COLECCIONES
GRANT SELECT, INSERT, UPDATE, DELETE ON DBMUSEO.COLECCIONES_PERMANENTES TO CURADOR;
GRANT SELECT ON DBMUSEO.SALAS_EXP TO CURADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBMUSEO.SALAS_COLECCIONES TO CURADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBMUSEO.EXPOSICIONES_EVENTOS TO CURADOR;
--PRIVILEGIOS SOBRE EL MANTENIMIENTO DE LAS OBRAS
GRANT SELECT, INSERT, UPDATE, DELETE ON DBMUSEO.PROGRAMAS_MANT TO CURADOR;
GRANT SELECT, INSERT, UPDATE ON DBMUSEO.MANTENIMIENTOS_OBRAS_REALIZADOS TO CURADOR;
--PROGRAMAS ALMACENADOS
GRANT EXECUTE ON DBMUSEO.SP_REGISTRAR_OBRA_NUEVA TO CURADOR;
GRANT EXECUTE ON DBMUSEO.SP_REGISTRAR_MANTENIMIENTO_OBRA TO CURADOR;
GRANT EXECUTE ON DBMUSEO.SP_MOVER_OBRA TO CURADOR;
GRANT EXECUTE ON DBMUSEO.SP_INSERTAR_COLECCION TO CURADOR;
GRANT EXECUTE ON DBMUSEO.SP_MODIFICAR_ORDEN_COLECCION TO CURADOR;
GRANT EXECUTE ON DBMUSEO.SP_ELIMINAR_COLECCION TO CURADOR;


--PRIVILEGIOS DE UN RESTAURADOR
-- EL RESTAURADOR SE ENCARGA DE RESTAURAR Y HACERLE MANTENIMIENTOS A LAS OBRAS
GRANT SELECT ON DBMUSEO.ARTISTAS TO RESTAURADOR;
GRANT SELECT ON DBMUSEO.OBRAS TO RESTAURADOR;
GRANT SELECT ON DBMUSEO.COLECCIONES_PERMANENTES TO RESTAURADOR;
GRANT SELECT ON DBMUSEO.PROGRAMAS_MANT TO RESTAURADOR;
GRANT SELECT, INSERT, UPDATE ON DBMUSEO.MANTENIMIENTOS_OBRAS_REALIZADOS TO RESTAURADOR;
GRANT SELECT ON DBMUSEO.HIST_OBRAS_MOV TO RESTAURADOR;
--PROGRAMAS ALMACENADOS
GRANT EXECUTE ON DBMUSEO.SP_REGISTRAR_MANTENIMIENTO_OBRA TO RESTAURADOR;

-- --PRIVILEGIOS DE FINANZAS
-- GRANT SELECT ON DBMUSEO.TICKETS TO FINANZAS;
-- GRANT SELECT, INSERT, UPDATE ON DBMUSEO.TIPO_TICKET TO FINANZAS;
-- GRANT SELECT ON DBMUSEO.EXPOSICIONES_EVENTOS TO FINANZAS;
-- --PROGRAMAS ALMACENADOS
-- GRANT EXECUTE ON DBMUSEO.INGRESOS_TOTAL_EVENTO_EXPO TO FINANZAS;
-- GRANT EXECUTE ON DBMUSEO.INGRESO_POR_EVENTO TO FINANZAS;

--PRIVILEGIOS DE RRHH
--PRIVILEGIOS SOBRE EMPLEADOS PROFESIONALES
GRANT SELECT, INSERT, UPDATE ON DBMUSEO.EMPLEADOS_PROFESIONALES TO RRHH;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBMUSEO.FORMACIONES TO RRHH;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBMUSEO.IDIOMAS TO RRHH;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBMUSEO.EMPLEADOS_IDIOMAS TO RRHH;
GRANT SELECT, INSERT, UPDATE ON DBMUSEO.HIST_EMPLEADOS TO RRHH;
--PRIVILEGIOS SOBRE EMPLEADOS DE VIGILANCIA O MANTENIMIENTO
GRANT SELECT, INSERT, UPDATE, DELETE ON DBMUSEO.EMPLEADOS_VIGILANTE_MANT TO RRHH;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBMUSEO.ASIGNACIONES_MES TO RRHH;
--PRIVILEGIOS SOBRE LA EST ORGANIZACIONAL DEL MUSEO
GRANT SELECT ON DBMUSEO.EST_ORGANIZACIONAL TO RRHH;
--PROGRAMAS ALMACENADOS
GRANT EXECUTE ON DBMUSEO.SP_MOVER_EMPLEADO_ACTIVO TO RRHH;
GRANT EXECUTE ON DBMUSEO.SP_MOVER_EMPLEADO_INACTIVO TO RRHH;
GRANT EXECUTE ON DBMUSEO.SP_REGISTRAR_NUEVO_EMPLEADO TO RRHH;
GRANT EXECUTE ON DBMUSEO.SP_REGISTRAR_VIGILANTE_MANT TO RRHH;

--PRIVILEGIOS DE VIGILANTE_MANTENIMIENTO
GRANT SELECT ON DBMUSEO.EST_FISICA TO VIGILANTE_MANTENIMIENTO;
GRANT SELECT ON DBMUSEO.SALAS_EXP TO VIGILANTE_MANTENIMIENTO;
GRANT SELECT ON DBMUSEO.ASIGNACIONES_MES TO VIGILANTE_MANTENIMIENTO;
GRANT SELECT ON DBMUSEO.CIERRES_TEMPORALES TO VIGILANTE_MANTENIMIENTO;

--PRIVILEGIOS DEL GESTOR DE ADMISIONES
GRANT SELECT ON DBMUSEO.TICKETS TO TAQUILLA;
GRANT SELECT ON DBMUSEO.TIPO_TICKETS TO TAQUILLA;
GRANT SELECT ON DBMUSEO.HORARIOS TO TAQUILLA;
GRANT SELECT ON DBMUSEO.EXPOSICIONES_EVENTOS TO TAQUILLA;
-- PROGRAMAS ALMACENADOS
GRANT EXECUTE ON DBMUSEO.SP_VENDER_TICKET TO TAQUILLA;


--PRIVILEGIOS DEL VISITANTE
GRANT SELECT ON DBMUSEO.MUSEOS TO VISITANTE;
GRANT SELECT ON DBMUSEO.HIST_MUSEOS TO VISITANTE;
GRANT SELECT ON DBMUSEO.OBRAS TO VISITANTE;
GRANT SELECT ON DBMUSEO.ARTISTAS TO VISITANTE;
GRANT SELECT ON DBMUSEO.COLECCIONES_PERMANENTES TO VISITANTE;
GRANT SELECT ON DBMUSEO.EXPOSICIONES_EVENTOS TO VISITANTE;
GRANT SELECT ON DBMUSEO.SALAS_EXP TO VISITANTE;
GRANT SELECT ON DBMUSEO.EST_FISICA TO VISITANTE;
GRANT SELECT ON DBMUSEO.HORARIOS TO VISITANTE;
GRANT SELECT ON DBMUSEO.TIPO_TICKETS TO VISITANTE;

--PRIVILEGIOS DEL DIRECTOR
GRANT SELECT, INSERT, UPDATE, DELETE ON DBMUSEO.LUGARES TO DIRECTOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBMUSEO.EST_ORGANIZACIONAL TO DIRECTOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBMUSEO.EST_FISICA TO DIRECTOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBMUSEO.HIST_MUSEOS TO DIRECTOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBMUSEO.HORARIOS TO DIRECTOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBMUSEO.CIERRES_TEMPORALES TO DIRECTOR;
GRANT SELECT, INSERT, UPDATE ON DBMUSEO.TIPO_TICKETS TO DIRECTOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBMUSEO.MUSEOS TO DIRECTOR;
GRANT SELECT ON DBMUSEO.HIST_EMPLEADOS TO DIRECTOR;
GRANT SELECT ON DBMUSEO.HIST_OBRAS_MOV TO DIRECTOR;
GRANT SELECT ON DBMUSEO.MANTENIMIENTOS_OBRAS_REALIZADOS TO DIRECTOR;
GRANT SELECT ON DBMUSEO.EXPOSICIONES_EVENTOS TO DIRECTOR;
GRANT SELECT ON DBMUSEO.ASIGNACIONES_MES TO DIRECTOR;
--VISTAS
GRANT SELECT ON DBMUSEO.V_MUSEOS_RANKING_SCORES TO DIRECTOR;
--PROGRAMAS ALMACENADOS
GRANT EXECUTE ON DBMUSEO.SP_CALCULAR_RANKING_MUSEO TO DIRECTOR;
GRANT EXECUTE ON DBMUSEO.SP_REGISTRAR_CIERRE_TEMPORAL TO DIRECTOR;



--DIRECTORES
CREATE USER LUKASZ IDENTIFIED BY 123456;
CREATE USER AGNIESZAKA IDENTIFIED BY 123456;
CREATE USER LOUIS IDENTIFIED BY 123456;
CREATE USER TOM IDENTIFIED BY 123456;
CREATE USER STEFAN IDENTIFIED BY 123456;
CREATE USER JEANNETTE IDENTIFIED BY 123456;
CREATE USER DIRECTOR01 IDENTIFIED BY 123456;
--PRIVILEGIOS DIRECTORES
GRANT DIRECTOR TO LUKASZ;
GRANT DIRECTOR TO AGNIESZAKA;
GRANT DIRECTOR TO LOUIS;
GRANT DIRECTOR TO TOM;
GRANT DIRECTOR TO STEFAN;
GRANT DIRECTOR TO JEANNETTE;
GRANT DIRECTOR TO DIRECTOR01;



--CURADORES
CREATE USER MARCIN IDENTIFIED BY 123456;
CREATE USER JAN IDENTIFIED BY 123456;
CREATE USER MONIKA IDENTIFIED BY 123456;
CREATE USER CARLOS IDENTIFIED BY 123456;
CREATE USER SOPHIE IDENTIFIED BY 123456;
CREATE USER ALICE IDENTIFIED BY 123456;
CREATE USER CURADOR01 IDENTIFIED BY 123456;
--PRIVILEGIOS CURADORES
GRANT CURADOR TO MARCIN;
GRANT CURADOR TO JAN;
GRANT CURADOR TO MONIKA;
GRANT CURADOR TO CARLOS;
GRANT CURADOR TO SOPHIE;
GRANT CURADOR TO ALICE;
GRANT CURADOR TO CURADOR01;

--RESTAURADORES
CREATE USER NATALIA IDENTIFIED BY 123456;
CREATE USER DAMIAN IDENTIFIED BY 123456;
CREATE USER JOSE IDENTIFIED BY 123456;
CREATE USER HUGO IDENTIFIED BY 123456;
CREATE USER RESTAURADOR01 IDENTIFIED BY 123456;
--PRIVILEGIOS RESTAURADORES
GRANT RESTAURADOR TO NATALIA;
GRANT RESTAURADOR TO DAMIAN;
GRANT RESTAURADOR TO JOSE;
GRANT RESTAURADOR TO HUGO;
GRANT RESTAURADOR TO RESTAURADOR01;

--RRHH
CREATE USER ANTOINE IDENTIFIED BY 123456;
CREATE USER GABRIEL IDENTIFIED BY 123456;
CREATE USER LEA IDENTIFIED BY 123456;
CREATE USER LISE IDENTIFIED BY 123456;
CREATE USER NATHA IDENTIFIED BY 123456;
CREATE USER RRHH01 IDENTIFIED BY 123456;
--PRIVILEGIOS RRHH
GRANT RRHH TO ANTOINE;
GRANT RRHH TO GABRIEL;
GRANT RRHH TO LEA;
GRANT RRHH TO LISE;
GRANT RRHH TO NATHA;
GRANT RRHH TO RRHH01;

--TAQUILLA
CREATE USER OLGA IDENTIFIED BY 123456;
CREATE USER ISTHARA IDENTIFIED BY 123456;
CREATE USER MARKO IDENTIFIED BY 123456;
CREATE USER LINDA IDENTIFIED BY 123456;
CREATE USER TAQUILLA01 IDENTIFIED BY 123456;
--PRIVILEGIOS TAQUILLA
GRANT TAQUILLA TO OLGA;
GRANT TAQUILLA TO ISTHARA;
GRANT TAQUILLA TO MARKO;
GRANT TAQUILLA TO LINDA;
GRANT TAQUILLA TO TAQUILLA01;

--VISITANTE
CREATE USER VISITANTE01 IDENTIFIED BY 123456;
CREATE USER VISITANTE02 IDENTIFIED BY 123456;
--PRIVILEGIOS VISITANTES
GRANT VISITANTE TO VISITANTE01;
GRANT VISITANTE TO VISITANTE02;

--VIGILANTE_MANTENIMIENTO
CREATE USER THADEUS IDENTIFIED BY 123456;
CREATE USER JOSEF IDENTIFIED BY 123456;
CREATE USER THEODORE IDENTIFIED BY 123456;
CREATE USER NIKOLAS IDENTIFIED BY 123456;
CREATE USER VIGILANTE01 IDENTIFIED BY 123456;
CREATE USER MANTENIMIENTO01 IDENTIFIED BY 123456;
--PRIVILEGIOS VIGILANTES_MANTENIMIENTO
GRANT VIGILANTE_MANTENIMIENTO TO THADEUS;
GRANT VIGILANTE_MANTENIMIENTO TO JOSEF;
GRANT VIGILANTE_MANTENIMIENTO TO THEODORE;
GRANT VIGILANTE_MANTENIMIENTO TO NIKOLAS;
GRANT VIGILANTE_MANTENIMIENTO TO VIGILANTE01;
GRANT VIGILANTE_MANTENIMIENTO TO MANTENIMIENTO01;